// The shipped declaration files (sdk/*.d.ts): generated by the real tsc
// from the author-visible modules (scripts/gen_declarations.mjs), never
// hand-written. This gate holds the committed files fresh against the
// sources and holds the generated surface ambient-clean — the global
// Uint8Array augmentation (sdk/bytes_text_methods.d.ts) must never leak
// into them, because it collides with other toolchains' lib typings.

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generateDeclarations, declarationSources } from "../scripts/gen_declarations.mjs";

const pkg = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const sdkDir = path.join(pkg, "sdk");

test("the committed sdk/*.d.ts are fresh against the sources", () => {
  const outputs = generateDeclarations();
  assert.deepEqual(
    [...outputs.keys()].sort(),
    declarationSources.map((s) => s.replace(/\.ts$/, ".d.ts")).sort(),
  );
  for (const [name, text] of outputs) {
    const committed = fs.readFileSync(path.join(sdkDir, name), "utf8");
    assert.equal(committed, text, `sdk/${name} is stale — run \`node scripts/gen_declarations.mjs\``);
  }
});

test("the generated declarations carry no ambient augmentation and no .ts specifiers", () => {
  for (const source of declarationSources) {
    const name = source.replace(/\.ts$/, ".d.ts");
    const text = fs.readFileSync(path.join(sdkDir, name), "utf8");
    assert.doesNotMatch(text, /declare\s+global/, name);
    assert.doesNotMatch(text, /interface\s+Uint8Array/, name);
    assert.doesNotMatch(text, /from\s+"\.[^"]*\.ts"/, name);
  }
});
